# Generated by Django 6.0.5 on 2026-05-19 06:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gudang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('namaGudang', models.CharField(max_length=50, unique=True, verbose_name='Nama Gudang')),
                ('alamat', models.CharField(max_length=255, verbose_name='Alamat')),
                ('kota', models.CharField(max_length=20, verbose_name='Kota')),
            ],
        ),
        migrations.CreateModel(
            name='TipeLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaLayanan', models.CharField(max_length=50, unique=True, verbose_name='Nama Layanan')),
                ('hargaPerKg', models.FloatField(verbose_name='Harga per Kg')),
                ('estHari', models.IntegerField(verbose_name='Estimasi Hari')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('noHp', models.CharField(max_length=15, verbose_name='Nomor Telepon')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('KURIR', 'Kurir'), ('CUSTOMER', 'Customer')], max_length=10, verbose_name='Role')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Bergabung')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100, verbose_name='Nama')),
                ('alamat', models.CharField(max_length=255, verbose_name='Alamat')),
                ('kota', models.CharField(max_length=20, verbose_name='Kota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Bergabung')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kurir',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idKurir', models.CharField(max_length=10, unique=True, verbose_name='ID Kurir')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama')),
                ('kota', models.CharField(max_length=20, verbose_name='Kota')),
                ('tipeKendaraan', models.CharField(max_length=20, verbose_name='Tipe Kendaraan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Bergabung')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kurir_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deskripsi', models.TextField(verbose_name='Deskripsi')),
                ('berat', models.FloatField(verbose_name='Berat (kg)')),
                ('dimensi', models.IntegerField(verbose_name='Dimensi (cm)')),
                ('ongkosKirim', models.FloatField(verbose_name='Ongkos Kirim')),
                ('status', models.CharField(choices=[('DIKEMAS', 'Dikemas'), ('DIKIRIM', 'Dikirim'), ('DITERIMA', 'Diterima')], default='DIKEMAS', max_length=20, verbose_name='Status')),
                ('penerima', models.CharField(max_length=100, verbose_name='Penerima')),
                ('alamatPenerima', models.CharField(max_length=255, verbose_name='Alamat Penerima')),
                ('kotaPenerima', models.CharField(max_length=20, verbose_name='Kota Penerima')),
                ('noHpPenerima', models.CharField(max_length=15, verbose_name='Nomor Telepon Penerima')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
                ('kurir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paket_kurir', to='tracking.kurir', verbose_name='Kurir')),
                ('pengirim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paket_pengirim', to='tracking.customer', verbose_name='Pengirim')),
                ('transitGudang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paket_gudang', to='tracking.gudang', verbose_name='Transit Gudang')),
                ('tipeLayanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.tipelayanan', verbose_name='Tipe Layanan')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('lokasi', models.CharField(max_length=255, verbose_name='Lokasi')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('kurir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_updates', to='tracking.kurir')),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tracking.paket')),
            ],
        ),
    ]
