# Generated by Django 6.0.5 on 2026-05-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_paket_resi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paket',
            name='status',
            field=models.CharField(choices=[('DIKEMAS', 'Dikemas'), ('DIKIRIM', 'Dikirim'), ('DITERIMA', 'Diterima'), ('DIBATALKAN', 'Dibatalkan')], default='DIKEMAS', max_length=20, verbose_name='Status'),
        ),
    ]
