# Generated by Django 6.0.5 on 2026-06-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_paket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paket',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Tanggal Diedit'),
        ),
    ]
