# Generated by Django 6.0.5 on 2026-06-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_paket_edited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paket',
            name='edited_at',
            field=models.DateTimeField(null=True, verbose_name='Tanggal Diedit'),
        ),
    ]
