# Generated by Django 6.0.5 on 2026-06-02 18:26

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_alter_paket_edited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paket',
            name='berat',
            field=models.FloatField(db_column='berat', verbose_name='Berat (kg)'),
        ),
        migrations.RenameField(
            model_name='paket',
            old_name='berat',
            new_name='_berat',
        ),
        migrations.AlterField(
            model_name='tipelayanan',
            name='hargaPerKg',
            field=models.FloatField(db_column='hargaPerKg', verbose_name='Harga per Kg'),
        ),
        migrations.RenameField(
            model_name='tipelayanan',
            old_name='hargaPerKg',
            new_name='_hargaPerKg',
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada'),
        ),
        migrations.AddField(
            model_name='gudang',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Dibuat Pada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gudang',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada'),
        ),
        migrations.AddField(
            model_name='kurir',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada'),
        ),
        migrations.AddField(
            model_name='paket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada'),
        ),
        migrations.AddField(
            model_name='tipelayanan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 6, 2, 18, 26, 44, 702126, tzinfo=datetime.timezone.utc), verbose_name='Dibuat Pada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipelayanan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada'),
        ),
        migrations.AddField(
            model_name='trackinghistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 6, 2, 18, 26, 50, 629953, tzinfo=datetime.timezone.utc), verbose_name='Dibuat Pada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackinghistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada'),
        ),
        migrations.AlterField(
            model_name='kurir',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada'),
        ),
        migrations.AlterField(
            model_name='paket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada'),
        ),
        migrations.AlterField(
            model_name='tipelayanan',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
